sudo: required
services:
  - docker

before_install:
  - docker build -t ab/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ab/react-test npm test -- --coverage

after_success:
  - docker build -t ab/multi-client ./client
  - docker build -t ab/multi-nginx ./nginx
  - docker build -t ab/multi-server ./server
  - docker build -t ab/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 
  # Take those images and push them to Docker Hub
  - docker push ab/multi-client
  - docker push ab/multi-nginx
  - docker push ab/multi-server
  - docker push ab/multi-worker