sudo: required
services:
  - docker

before_install:
  - docker build -t squirrelhouse/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run squirrelhouse/react-test npm test -- --coverage

after_success:
  - docker build -t squirrelhouse/multi-client ./client
  - docker build -t squirrelhouse/multi-nginx ./nginx
  - docker build -t squirrelhouse/multi-server ./server
  - docker build -t squirrelhouse/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 
  # Take those images and push them to Docker Hub
  - docker push squirrelhouse/multi-client
  - docker push squirrelhouse/multi-nginx
  - docker push squirrelhouse/multi-server
  - docker push squirrelhouse/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: us-west-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-west-2-423845497921
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
      secure: "$AWS_SECRET_KEY"